import meshio
import numpy as np

# Read the .msh file generated by Gmsh
msh = meshio.read("malha.msh")

# Extract triangle data
triangle_cells = msh.cells_dict["triangle"]
triangle_data = msh.cell_data_dict["gmsh:physical"]["triangle"]

# Create a new mesh with only triangles and the physical tags
meshio.write_points_cells(
    "malha.xdmf",
    msh.points,
    [("triangle", triangle_cells)],
    cell_data={"cell_tags": [triangle_data]}
)
print("Conversion to malha.xdmf complete!")